name: CI
on:
  push:
    branches:
    - '*'

jobs:
  BuildBinaries:
    name: Build application packages
    strategy:
      matrix:
        runtime: [ linux-x64, linux-fedora-x64, ]
        include:
          - runtime: linux-x64
            arch: x64
            os: ubuntu-latest
            shell: bash
            build: packageUberJarForCurrentOS packageDeb
            setupCl: ./scripts/SetupClUnix.sh

          - runtime: linux-fedora-x64
            arch: x64
            os: ubuntu-latest
            shell: bash
            build: packageRpm
            setupCl: ./scripts/SetupClUnix.sh

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v1
        if: ${{ matrix.runtime != 'linux-fedora-x64' }}
        with:
          java-version: '17'
          architecture: ${{ matrix.arch }}

      - name: Setup Cl
        run: ${{ matrix.setupCl }}

      - name: Build rpm Package
        if: ${{ matrix.runtime == 'linux-fedora-x64' }}
        uses: Syer10/Fedora-Java17-Action@v1
        with:
          command: ./gradlew ${{ matrix.build }} --stacktrace

      - name: Build
        if: ${{ matrix.runtime != 'linux-fedora-x64' }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: >
            ${{ matrix.build }}
            -Pcompose.desktop.mac.sign=true
            -Pcompose.desktop.mac.signing.identity=${{ secrets.APPLE_IDENTITY_SHORT }}
            -Pcompose.desktop.mac.notarization.appleID=${{ secrets.APPLE_ID }}
            -Pcompose.desktop.mac.notarization.password=${{ secrets.APPLE_PASSWORD }}
            -Pidentity="${{ secrets.APPLE_IDENTITY }}"

      # Upload runner package tar.gz/zip as artifact
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: runner-package-${{ matrix.runtime }}
          path: |
            desktop/build/compose/binaries/main/*/
            desktop/build/compose/jars/
            !desktop/build/compose/binaries/main/app/
            ${{ env.SIGNED_RELEASE_FILE }}

        # Upload runner errors
      - name: Upload error logs
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: runner-errors-${{ matrix.runtime }}
          path: |
            desktop/build/compose/logs/
  ReleaseBinaries:
    name: Make a release
    needs: [ BuildBinaries ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download Build Artifacts
        uses: actions/download-artifact@v2

      - name: Fix rpm java dependency
        uses: Syer10/Fedora-Java17-Action@v1
        with:
          command: ./scripts/RpmDependencyFix.sh

      - name: Fix deb java dependency
        run: ./scripts/DebDependencyFix.sh

      - name: Fix filenames
        run: ./scripts/NamingFix.sh

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*/binaries/main/*/*.*,*/jars/*.jar,*/android/build/outputs/apk/release/*.apk"
          draft: true
          token: ${{ secrets.WINGET_PUBLISH_PAT }}
